### ISSUE TITLE
plot_explanations() throws "Unknown or uninitialised column: `label`" warning for regression models

### ISSUE THREAD

**Issue by agilebean** [ModelOriented/DALEX#422] opened 2021-05-19 15:17 UTC
It seems that this warning is only issued for regression models.

```
some_regression_model %>% plot_explanations()
Warning message:
Unknown or uninitialised column: `label`.
```
This warning is thrown by a tibble when testing whether `label` exists.
I suggest to replace it by `has_name()` as jennybc from Rstudio suggested [here](https://github.com/tidyverse/tibble/issues/450#issuecomment-411153817).

**Comment by pbiecek** [comment] 2021-05-31 19:22
do you have a reproducible example generating this error?

**Comment by hbaniecki** [comment] 2021-06-07 13:55
closing due to no reproducible code example

**Closed by hbaniecki** 2021-06-07 13:55 UTC
Labels: R 🐳
